analysis:
    nbins: 2
    nside: 256
    gn:
        a: 0.65397488, 0.52029803
        b: 0.36216059, 0.24023071
        c: 2.81548633, 2.25700888

io:
    input_dir: /spiff/ssage/karmma_data/LN_dg_RS_linmu/Inputs/
    output_dir: /spiff/ssage/karmma_data/LN_dg_RS_linmu/
    datafile: mock_dg.h5
    init_file: null
    theta_file: theta_true.h5
    cl_file: cl_sim42.npy
    pixwin: pixwin_256.npy

mcmc:
    sampler: nuts
    infer_theta: true
    seed: null
    num_warmup: 200
    n_samples: 400
    step_size: 0.0001
    target_acceptance_rate: null
